version: '3.1'

services:

  accompaniator:
    image: accompaniator
    build: accompaniator
    devices:
      - /dev/snd:/dev/snd
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /run/dbus/:/run/dbus/:rw
      - /dev/shm:/dev/shm

  accompaniator-dev:
    image: accompaniator-dev
    build: accompaniator-dev
    devices:
      - /dev/snd:/dev/snd
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /run/dbus/:/run/dbus/:rw
      - /dev/shm:/dev/shm
      - ./../:/build/accompaniator

  accompaniator-prod:
    image: accompaniator-prod
    build: accompaniator-prod
    devices:
      - /dev/snd:/dev/snd
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /run/dbus/:/run/dbus/:rw
      - /dev/shm:/dev/shm
